spring.application.name=task12

spring.datasource.url=jdbc:mysql://localhost:3306/verb
spring.datasource.username=root
spring.datasource.password=pass123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
